baseurl: "/" # the subpath of your site, e.g. /blog
encoding: utf-8

# Build settings
theme: null
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gzip # compress assets
    - jekyll-seo-tag # to fix: robots.txt is not valid

markdown: kramdown
# highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false
    math_engine: mathjax
    smart_quotes: ["apos", "apos", "quot", "quot"]
    # syntax_highlighter: rouge

sass:
    style: compressed

collections:
    notes:
        output: true
        permalink: /notes/:title
    projects:
        output: true
        permalink: /projects/:title
    publications:
        output: true
        permalink: /publications/:title

defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          permalink: /posts/:title
          content-type: post

include: ["_pages", "_projects", "_publications"]
exclude: ["_notes/Templates"]
