title: "madebymaze.xyz"
description: "I like Deep Learning"
permalink: ':title/'
baseurl: ""
url: ""

# Paginate
paginate: 8
paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
kramdown:
  input: GFM #Github Flavored Markdown
  hard_wrap: false  
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - minima
  - jekyll-feed
  - jekyll-toc
  - jekyll-numbered-headings
include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
